import express from 'express';
import registerUser from '../controllers/user/register.js';
import login from '../controllers/user/login.js';
import getUser from '../controllers/user/getUser.js';
import isLoggedIn from '../middlewares/isloggedIn.js';
import logout from '../controllers/user/logout.js';
import getAccess from '../controllers/user/getAccess.js';
import forgotPassword from '../controllers/user/forgotPassword.js';
import verifyOtp from '../controllers/user/verifyOtp.js';
import getTime from '../controllers/user/getTime.js';
import updatePassword from '../controllers/user/updatePassword.js';
import verifyUser from "../controllers/user/verifyUser.js";

const router = express.Router();
router.post('/register', registerUser); 
router.post('/login', login);
router.get('/',isLoggedIn, getUser);
router.get('/logout', logout);
router.get('/access', isLoggedIn, getAccess);
router.post('/forgot-password', forgotPassword);
router.post('/verify-otp', verifyOtp);
router.post('/get-time', getTime);
router.post('/update-password',isLoggedIn, updatePassword);
router.get("/verify", verifyUser);
export default router;